# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=personas
      - MYSQL_USER=alvaro
      - MYSQL_PASSWORD=alvaro123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: